version: '3.3'
services:

  eventProcessor:
    image: coreserver:latest
    command:
      - node
      - "lib/ethEventProcessor.js"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.rebalancer.no-overlap: "true"
      ofelia.job-exec.rebalancer.schedule: "@every 10s"
      ofelia.job-exec.rebalancer.command: "node lib/rebalancer.js"
  
  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro